# Generated by Django 4.0.7 on 2022-11-26 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('GOVERNMENT', 'Government')], default='RESIDENTIAL', max_length=12)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectExhibition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Exhibition',
                'verbose_name_plural': 'Project Exhibitions',
            },
        ),
        migrations.CreateModel(
            name='ProjectExhibitionTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_testimonial', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=50)),
                ('testimonial', models.TextField(max_length=350)),
                ('star_rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projectexhibition')),
            ],
            options={
                'verbose_name': 'Project Testimonial',
                'verbose_name_plural': 'Project Testimonials',
            },
        ),
        migrations.CreateModel(
            name='ProjectExhibitionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projectexhibition')),
            ],
            options={
                'verbose_name': 'Project Product',
                'verbose_name_plural': 'Project Products',
            },
        ),
        migrations.CreateModel(
            name='ProjectExhibitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='project_gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectexhibition')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
