# Generated by Django 4.0.7 on 2022-11-26 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('announcement', models.FileField(upload_to='announcements/')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='OperationBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('start_time', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('\\d{1,2}:\\d\\d [pa]m', 'Please enter a start time in the xx:xx pm/am format.')])),
                ('end_time', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('\\d{1,2}:\\d\\d [pa]m', 'Please enter an end time in the xx:xx pm/am format.')])),
            ],
            options={
                'verbose_name': 'Operation Block',
                'verbose_name_plural': 'Operation Blocks',
            },
        ),
        migrations.CreateModel(
            name='QandACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Q&A Category',
                'verbose_name_plural': 'Q&A Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('banner', models.FileField(upload_to='service_areas/')),
                ('service_type', models.CharField(choices=[('AC', 'All Cities'), ('SC', 'Select Cities')], default='SC', max_length=2)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
            },
        ),
        migrations.CreateModel(
            name='TermandConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('section_name', models.CharField(max_length=75)),
                ('section_tc', models.TextField()),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=150)),
                ('answer', models.TextField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.qandacategory')),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': "Q&A's",
                'ordering': ('category',),
            },
        ),
    ]
