# Generated by Django 4.0.7 on 2022-11-26 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationblocks',
            name='end_time',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('\\d{1,2}:\\d\\d [pa]m', 'Please enter an end time in the xx:xx pm/am format.')]),
        ),
        migrations.AlterField(
            model_name='operationblocks',
            name='start_time',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('\\d{1,2}:\\d\\d [pa]m', 'Please enter a start time in the xx:xx pm/am format.')]),
        ),
    ]
