# Generated by Django 4.0.7 on 2022-11-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_operationblocks_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us Text',
                'verbose_name_plural': 'About Us Text',
            },
        ),
    ]
