# Generated by Django 4.0.7 on 2022-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmore',
            name='available_to_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesmore',
            name='available_to_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmore',
            name='available_to_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('STAFF', 'Staff'), ('SALES', 'Sales'), ('CONSTRUCTION', 'Construction'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20, verbose_name='Type'),
        ),
    ]
